---
name: Checks
"on":
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  check-all-the-things:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version: "1.21"
          cache: true

      - name: Checkov scan
        run: |
          docker run --rm \
            -v "$PWD":/work \
            -w /work \
            bridgecrew/checkov:2.0.930@sha256:079148f3df7777a62f196f1ffdbaeca5b41a72a3a66412df1d4a5cecc6aaf08a \
            -d . \
            --framework github_actions \
            --skip-check CKV_GHA_7,CKV2_GHA_1 \
            --quiet \
            --soft-fail \
            -o cli

      - name: Checkov annotations
        run: |
          docker run --rm \
            -v "$PWD":/work \
            -w /work \
            bridgecrew/checkov:2.0.930@sha256:079148f3df7777a62f196f1ffdbaeca5b41a72a3a66412df1d4a5cecc6aaf08a \
            -d . \
            --framework github_actions \
            --skip-check CKV_GHA_7,CKV2_GHA_1 \
            --quiet \
            --soft-fail \
            -o github_failed_only

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .github/workflows
          format: github

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.11.4
